#!/usr/bin/env bash
# ps5-homebrew-ui - OpenGL SDK link preparation.
# Copyright (C) 2026 BlackBearReloaded
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Selects the ps5-opengl SDK (PS5_OPENGL_PREFIX, or the pinned release), exposes
# it at .deps/ps5-opengl/current and writes the linker group the build links.

set -euo pipefail

root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
bash "$root/tools/setup-native-dependencies.sh" >/dev/null
sdk="$root/.deps/native/ps5-payload-sdk"

if [[ -n ${PS5_OPENGL_PREFIX:-} ]]; then
    prefix=$(realpath -e -- "$PS5_OPENGL_PREFIX")
    (cd "$prefix" && sha256sum --check --strict --quiet manifest.sha256) || {
        echo "PS5_OPENGL_PREFIX manifest verification failed: $prefix" >&2
        exit 2
    }
else
    prefix=$(bash "$root/tools/fetch-opengl-sdk.sh")
fi

for required in include/EGL/egl.h include/GL/glcorearb.h include/ps5_opengl_display.h \
    lib/libPS5OpenGL.a lib/libSceAgc.so lib/libSceAgcDriver.so; do
    [[ -f $prefix/$required ]] || { echo "ps5-opengl SDK is missing $required" >&2; exit 2; }
done

cache="$root/.deps/ps5-opengl"
mkdir -p "$cache"
link_target="$prefix"
if [[ $prefix == "$cache/"* ]]; then
    link_target=${prefix#"$cache/"}
fi
ln -sfn -- "$link_target" "$cache/current"

compiler=$(command -v "${PS5_CLANG:-clang-18}")
builtins="$("$compiler" --print-resource-dir)/lib/linux/libclang_rt.builtins-x86_64.a"
for library in "$sdk/target/lib/libunwind.a" "$sdk/target/lib/libc++abi.a" \
    "$sdk/target/lib/libc++.a" "$builtins"; do
    [[ -s $library ]] || { echo "missing link input: $library" >&2; exit 2; }
done

group="$cache/libps5opengl-group.a"
{
    printf '/* Generated by tools/prepare-opengl.sh; do not edit. */\n'
    printf 'SEARCH_DIR("%s")\n' "$prefix/lib" "$sdk/target/lib"
    # The runtime entry is only reachable through the driver's dispatch table.
    printf 'EXTERN(ps5_agc_gate2_run)\n'
    printf 'GROUP (\n'
    printf '  "%s"\n' "$prefix/lib/libPS5OpenGL.a" "$sdk/target/lib/libunwind.a" \
        "$sdk/target/lib/libc++abi.a" "$sdk/target/lib/libc++.a" "$builtins"
    printf ')\n'
} > "$group.tmp"
if ! cmp -s "$group.tmp" "$group"; then
    mv -- "$group.tmp" "$group"
else
    rm -f -- "$group.tmp"
fi

manifest=$(sha256sum "$prefix/manifest.sha256" | cut -d' ' -f1)
profile=$(grep -E '#define PS5_OPENGL_NATIVE_(WIDTH|HEIGHT|FPS)' \
    "$prefix/include/ps5_opengl_display.h" | awk '{print $3}' | paste -sd' ')
printf 'OpenGL SDK: %s\nOpenGL SDK manifest: %s\nOpenGL display profile (w h fps): %s\n' \
    "$prefix" "$manifest" "$profile"
